# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1394, 949)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 150, 1321, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_student = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_student.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_student.setObjectName("btn_student")
        self.verticalLayout.addWidget(self.btn_student)
        self.btn_course = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_course.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_course.setObjectName("btn_course")
        self.verticalLayout.addWidget(self.btn_course)
        self.btn_major = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_major.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_major.setObjectName("btn_major")
        self.verticalLayout.addWidget(self.btn_major)
        self.btn_major_change = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_major_change.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_major_change.setObjectName("btn_major_change")
        self.verticalLayout.addWidget(self.btn_major_change)
        self.btn_grade = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_grade.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_grade.setObjectName("btn_grade")
        self.verticalLayout.addWidget(self.btn_grade)
        self.btn_award_punishment = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_award_punishment.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_award_punishment.setObjectName("btn_award_punishment")
        self.verticalLayout.addWidget(self.btn_award_punishment)
        self.horizontalLayout_25.addLayout(self.verticalLayout)
        self.table_management = QtWidgets.QStackedWidget(self.layoutWidget)
        self.table_management.setObjectName("table_management")
        self.student_page = QtWidgets.QWidget()
        self.student_page.setObjectName("student_page")
        self.layoutWidget1 = QtWidgets.QWidget(self.student_page)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 1131, 459))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.student_table = QtWidgets.QTableWidget(self.layoutWidget1)
        self.student_table.setMinimumSize(QtCore.QSize(0, 250))
        self.student_table.setObjectName("student_table")
        self.student_table.setColumnCount(0)
        self.student_table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.student_table)
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sno_search = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sno_search.setMinimumSize(QtCore.QSize(50, 0))
        self.sno_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sno_search.setObjectName("sno_search")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sno_search)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sname_search = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sname_search.setMinimumSize(QtCore.QSize(80, 0))
        self.sname_search.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sname_search.setObjectName("sname_search")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sname_search)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sex_search = QtWidgets.QComboBox(self.layoutWidget1)
        self.sex_search.setMinimumSize(QtCore.QSize(120, 0))
        self.sex_search.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sex_search.setObjectName("sex_search")
        self.sex_search.addItem("")
        self.sex_search.setItemText(0, "")
        self.sex_search.addItem("")
        self.sex_search.addItem("")
        self.sex_search.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sex_search)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.smno_search = QtWidgets.QLineEdit(self.layoutWidget1)
        self.smno_search.setMinimumSize(QtCore.QSize(50, 0))
        self.smno_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.smno_search.setObjectName("smno_search")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.smno_search)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setObjectName("label_14")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.sgrade_search = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sgrade_search.setMinimumSize(QtCore.QSize(50, 0))
        self.sgrade_search.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sgrade_search.setObjectName("sgrade_search")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sgrade_search)
        self.horizontalLayout.addLayout(self.formLayout_14)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.syear_search = QtWidgets.QLineEdit(self.layoutWidget1)
        self.syear_search.setMinimumSize(QtCore.QSize(50, 0))
        self.syear_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.syear_search.setObjectName("syear_search")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.syear_search)
        self.horizontalLayout.addLayout(self.formLayout_5)
        self.btn_student_search = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_student_search.setObjectName("btn_student_search")
        self.horizontalLayout.addWidget(self.btn_student_search)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.sno_insert = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sno_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.sno_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sno_insert.setObjectName("sno_insert")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sno_insert)
        self.horizontalLayout_2.addLayout(self.formLayout_6)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.sname_insert = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sname_insert.setMinimumSize(QtCore.QSize(80, 0))
        self.sname_insert.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sname_insert.setObjectName("sname_insert")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sname_insert)
        self.horizontalLayout_2.addLayout(self.formLayout_7)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.sex_insert = QtWidgets.QComboBox(self.layoutWidget1)
        self.sex_insert.setMinimumSize(QtCore.QSize(120, 0))
        self.sex_insert.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sex_insert.setObjectName("sex_insert")
        self.sex_insert.addItem("")
        self.sex_insert.addItem("")
        self.sex_insert.addItem("")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sex_insert)
        self.horizontalLayout_2.addLayout(self.formLayout_8)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.smno_insert = QtWidgets.QLineEdit(self.layoutWidget1)
        self.smno_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.smno_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.smno_insert.setObjectName("smno_insert")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.smno_insert)
        self.horizontalLayout_2.addLayout(self.formLayout_9)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.syear_insert = QtWidgets.QLineEdit(self.layoutWidget1)
        self.syear_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.syear_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.syear_insert.setObjectName("syear_insert")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.syear_insert)
        self.horizontalLayout_2.addLayout(self.formLayout_10)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.sphone_insert = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sphone_insert.setMinimumSize(QtCore.QSize(80, 0))
        self.sphone_insert.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sphone_insert.setObjectName("sphone_insert")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sphone_insert)
        self.horizontalLayout_2.addLayout(self.formLayout_11)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.sphoto_insert = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sphoto_insert.setMinimumSize(QtCore.QSize(80, 0))
        self.sphoto_insert.setMaximumSize(QtCore.QSize(120, 16777215))
        self.sphoto_insert.setObjectName("sphoto_insert")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sphoto_insert)
        self.horizontalLayout_2.addLayout(self.formLayout_12)
        self.btn_student_insert = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_student_insert.setObjectName("btn_student_insert")
        self.horizontalLayout_2.addWidget(self.btn_student_insert)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_15 = QtWidgets.QFormLayout()
        self.formLayout_15.setObjectName("formLayout_15")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setObjectName("label_15")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.sno_update = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sno_update.setMinimumSize(QtCore.QSize(50, 0))
        self.sno_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sno_update.setObjectName("sno_update")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sno_update)
        self.horizontalLayout_3.addLayout(self.formLayout_15)
        self.formLayout_16 = QtWidgets.QFormLayout()
        self.formLayout_16.setObjectName("formLayout_16")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.sname_update = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sname_update.setMinimumSize(QtCore.QSize(50, 0))
        self.sname_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sname_update.setObjectName("sname_update")
        self.formLayout_16.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sname_update)
        self.horizontalLayout_3.addLayout(self.formLayout_16)
        self.formLayout_17 = QtWidgets.QFormLayout()
        self.formLayout_17.setObjectName("formLayout_17")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setObjectName("label_17")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.sex_update = QtWidgets.QComboBox(self.layoutWidget1)
        self.sex_update.setMinimumSize(QtCore.QSize(120, 0))
        self.sex_update.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sex_update.setObjectName("sex_update")
        self.sex_update.addItem("")
        self.sex_update.setItemText(0, "")
        self.sex_update.addItem("")
        self.sex_update.addItem("")
        self.sex_update.addItem("")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sex_update)
        self.horizontalLayout_3.addLayout(self.formLayout_17)
        self.formLayout_20 = QtWidgets.QFormLayout()
        self.formLayout_20.setObjectName("formLayout_20")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setObjectName("label_20")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.sphone_update = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sphone_update.setMinimumSize(QtCore.QSize(80, 0))
        self.sphone_update.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sphone_update.setObjectName("sphone_update")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sphone_update)
        self.horizontalLayout_3.addLayout(self.formLayout_20)
        self.formLayout_21 = QtWidgets.QFormLayout()
        self.formLayout_21.setObjectName("formLayout_21")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setObjectName("label_21")
        self.formLayout_21.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.sphoto_update = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sphoto_update.setMinimumSize(QtCore.QSize(80, 0))
        self.sphoto_update.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sphoto_update.setObjectName("sphoto_update")
        self.formLayout_21.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sphoto_update)
        self.horizontalLayout_3.addLayout(self.formLayout_21)
        self.btn_student_update = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_student_update.setObjectName("btn_student_update")
        self.horizontalLayout_3.addWidget(self.btn_student_update)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_18 = QtWidgets.QFormLayout()
        self.formLayout_18.setObjectName("formLayout_18")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setObjectName("label_18")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.sno_delete = QtWidgets.QLineEdit(self.layoutWidget1)
        self.sno_delete.setMinimumSize(QtCore.QSize(50, 0))
        self.sno_delete.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sno_delete.setObjectName("sno_delete")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sno_delete)
        self.horizontalLayout_4.addLayout(self.formLayout_18)
        self.btn_student_delete = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_student_delete.setObjectName("btn_student_delete")
        self.horizontalLayout_4.addWidget(self.btn_student_delete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.table_management.addWidget(self.student_page)
        self.course_page = QtWidgets.QWidget()
        self.course_page.setObjectName("course_page")
        self.layoutWidget2 = QtWidgets.QWidget(self.course_page)
        self.layoutWidget2.setGeometry(QtCore.QRect(360, 10, 471, 459))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.course_table = QtWidgets.QTableWidget(self.layoutWidget2)
        self.course_table.setMinimumSize(QtCore.QSize(0, 300))
        self.course_table.setObjectName("course_table")
        self.course_table.setColumnCount(0)
        self.course_table.setRowCount(0)
        self.verticalLayout_4.addWidget(self.course_table)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_19 = QtWidgets.QFormLayout()
        self.formLayout_19.setObjectName("formLayout_19")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setObjectName("label_19")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.cno_search = QtWidgets.QLineEdit(self.layoutWidget2)
        self.cno_search.setMinimumSize(QtCore.QSize(50, 0))
        self.cno_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cno_search.setObjectName("cno_search")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cno_search)
        self.horizontalLayout_5.addLayout(self.formLayout_19)
        self.formLayout_22 = QtWidgets.QFormLayout()
        self.formLayout_22.setObjectName("formLayout_22")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_22.setObjectName("label_22")
        self.formLayout_22.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.cname_search = QtWidgets.QLineEdit(self.layoutWidget2)
        self.cname_search.setMinimumSize(QtCore.QSize(80, 0))
        self.cname_search.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cname_search.setObjectName("cname_search")
        self.formLayout_22.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cname_search)
        self.horizontalLayout_5.addLayout(self.formLayout_22)
        self.btn_course_search = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_course_search.setObjectName("btn_course_search")
        self.horizontalLayout_5.addWidget(self.btn_course_search)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_27 = QtWidgets.QFormLayout()
        self.formLayout_27.setObjectName("formLayout_27")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_27.setObjectName("label_27")
        self.formLayout_27.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.cno_insert = QtWidgets.QLineEdit(self.layoutWidget2)
        self.cno_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.cno_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cno_insert.setObjectName("cno_insert")
        self.formLayout_27.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cno_insert)
        self.horizontalLayout_6.addLayout(self.formLayout_27)
        self.formLayout_28 = QtWidgets.QFormLayout()
        self.formLayout_28.setObjectName("formLayout_28")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_28.setObjectName("label_28")
        self.formLayout_28.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.cname_insert = QtWidgets.QLineEdit(self.layoutWidget2)
        self.cname_insert.setMinimumSize(QtCore.QSize(80, 0))
        self.cname_insert.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cname_insert.setObjectName("cname_insert")
        self.formLayout_28.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cname_insert)
        self.horizontalLayout_6.addLayout(self.formLayout_28)
        self.btn_course_insert = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_course_insert.setObjectName("btn_course_insert")
        self.horizontalLayout_6.addWidget(self.btn_course_insert)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_34 = QtWidgets.QFormLayout()
        self.formLayout_34.setObjectName("formLayout_34")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_34.setObjectName("label_34")
        self.formLayout_34.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.cno_update = QtWidgets.QLineEdit(self.layoutWidget2)
        self.cno_update.setMinimumSize(QtCore.QSize(50, 0))
        self.cno_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cno_update.setObjectName("cno_update")
        self.formLayout_34.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cno_update)
        self.horizontalLayout_7.addLayout(self.formLayout_34)
        self.formLayout_35 = QtWidgets.QFormLayout()
        self.formLayout_35.setObjectName("formLayout_35")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_35.setObjectName("label_35")
        self.formLayout_35.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.cname_update = QtWidgets.QLineEdit(self.layoutWidget2)
        self.cname_update.setMinimumSize(QtCore.QSize(50, 0))
        self.cname_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cname_update.setObjectName("cname_update")
        self.formLayout_35.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cname_update)
        self.horizontalLayout_7.addLayout(self.formLayout_35)
        self.btn_course_update = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_course_update.setObjectName("btn_course_update")
        self.horizontalLayout_7.addWidget(self.btn_course_update)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.table_management.addWidget(self.course_page)
        self.major_page = QtWidgets.QWidget()
        self.major_page.setObjectName("major_page")
        self.layoutWidget_3 = QtWidgets.QWidget(self.major_page)
        self.layoutWidget_3.setGeometry(QtCore.QRect(320, 10, 451, 459))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.major_table = QtWidgets.QTableWidget(self.layoutWidget_3)
        self.major_table.setMinimumSize(QtCore.QSize(0, 300))
        self.major_table.setObjectName("major_table")
        self.major_table.setColumnCount(0)
        self.major_table.setRowCount(0)
        self.verticalLayout_6.addWidget(self.major_table)
        spacerItem2 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.formLayout_23 = QtWidgets.QFormLayout()
        self.formLayout_23.setObjectName("formLayout_23")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.formLayout_23.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.mno_search = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.mno_search.setMinimumSize(QtCore.QSize(50, 0))
        self.mno_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.mno_search.setObjectName("mno_search")
        self.formLayout_23.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mno_search)
        self.horizontalLayout_8.addLayout(self.formLayout_23)
        self.formLayout_24 = QtWidgets.QFormLayout()
        self.formLayout_24.setObjectName("formLayout_24")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.formLayout_24.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.mname_search = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.mname_search.setMinimumSize(QtCore.QSize(80, 0))
        self.mname_search.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mname_search.setObjectName("mname_search")
        self.formLayout_24.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mname_search)
        self.horizontalLayout_8.addLayout(self.formLayout_24)
        self.btn_major_search = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_major_search.setObjectName("btn_major_search")
        self.horizontalLayout_8.addWidget(self.btn_major_search)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout_29 = QtWidgets.QFormLayout()
        self.formLayout_29.setObjectName("formLayout_29")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.formLayout_29.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.mno_insert = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.mno_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.mno_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.mno_insert.setObjectName("mno_insert")
        self.formLayout_29.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mno_insert)
        self.horizontalLayout_9.addLayout(self.formLayout_29)
        self.formLayout_30 = QtWidgets.QFormLayout()
        self.formLayout_30.setObjectName("formLayout_30")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.formLayout_30.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.mname_insert = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.mname_insert.setMinimumSize(QtCore.QSize(80, 0))
        self.mname_insert.setMaximumSize(QtCore.QSize(120, 16777215))
        self.mname_insert.setObjectName("mname_insert")
        self.formLayout_30.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mname_insert)
        self.horizontalLayout_9.addLayout(self.formLayout_30)
        self.btn_major_insert = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_major_insert.setObjectName("btn_major_insert")
        self.horizontalLayout_9.addWidget(self.btn_major_insert)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.formLayout_36 = QtWidgets.QFormLayout()
        self.formLayout_36.setObjectName("formLayout_36")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_36.setObjectName("label_36")
        self.formLayout_36.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.mno_update = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.mno_update.setMinimumSize(QtCore.QSize(50, 0))
        self.mno_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.mno_update.setObjectName("mno_update")
        self.formLayout_36.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mno_update)
        self.horizontalLayout_10.addLayout(self.formLayout_36)
        self.formLayout_37 = QtWidgets.QFormLayout()
        self.formLayout_37.setObjectName("formLayout_37")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.formLayout_37.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.mname_update = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.mname_update.setMinimumSize(QtCore.QSize(50, 0))
        self.mname_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.mname_update.setObjectName("mname_update")
        self.formLayout_37.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mname_update)
        self.horizontalLayout_10.addLayout(self.formLayout_37)
        self.btn_major_update = QtWidgets.QPushButton(self.layoutWidget_3)
        self.btn_major_update.setObjectName("btn_major_update")
        self.horizontalLayout_10.addWidget(self.btn_major_update)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.table_management.addWidget(self.major_page)
        self.major_change_page = QtWidgets.QWidget()
        self.major_change_page.setObjectName("major_change_page")
        self.layoutWidget_2 = QtWidgets.QWidget(self.major_change_page)
        self.layoutWidget_2.setGeometry(QtCore.QRect(100, 10, 911, 459))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.major_change_table = QtWidgets.QTableWidget(self.layoutWidget_2)
        self.major_change_table.setMinimumSize(QtCore.QSize(0, 250))
        self.major_change_table.setObjectName("major_change_table")
        self.major_change_table.setColumnCount(0)
        self.major_change_table.setRowCount(0)
        self.verticalLayout_10.addWidget(self.major_change_table)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.formLayout_51 = QtWidgets.QFormLayout()
        self.formLayout_51.setObjectName("formLayout_51")
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.formLayout_51.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.csno_search = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.csno_search.setMinimumSize(QtCore.QSize(50, 0))
        self.csno_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.csno_search.setObjectName("csno_search")
        self.formLayout_51.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.csno_search)
        self.horizontalLayout_15.addLayout(self.formLayout_51)
        self.formLayout_54 = QtWidgets.QFormLayout()
        self.formLayout_54.setObjectName("formLayout_54")
        self.label_54 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_54.setObjectName("label_54")
        self.formLayout_54.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.cmno_from_search = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.cmno_from_search.setMinimumSize(QtCore.QSize(50, 0))
        self.cmno_from_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmno_from_search.setObjectName("cmno_from_search")
        self.formLayout_54.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmno_from_search)
        self.horizontalLayout_15.addLayout(self.formLayout_54)
        self.formLayout_55 = QtWidgets.QFormLayout()
        self.formLayout_55.setObjectName("formLayout_55")
        self.label_55 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_55.setObjectName("label_55")
        self.formLayout_55.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.cmno_to_search = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.cmno_to_search.setMinimumSize(QtCore.QSize(50, 0))
        self.cmno_to_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmno_to_search.setObjectName("cmno_to_search")
        self.formLayout_55.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmno_to_search)
        self.horizontalLayout_15.addLayout(self.formLayout_55)
        self.formLayout_56 = QtWidgets.QFormLayout()
        self.formLayout_56.setObjectName("formLayout_56")
        self.label_56 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.formLayout_56.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.cyear_search = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.cyear_search.setMinimumSize(QtCore.QSize(50, 0))
        self.cyear_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cyear_search.setObjectName("cyear_search")
        self.formLayout_56.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cyear_search)
        self.horizontalLayout_15.addLayout(self.formLayout_56)
        self.btn_major_change_search = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_major_change_search.setObjectName("btn_major_change_search")
        self.horizontalLayout_15.addWidget(self.btn_major_change_search)
        self.verticalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.formLayout_52 = QtWidgets.QFormLayout()
        self.formLayout_52.setObjectName("formLayout_52")
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.formLayout_52.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.csno_insert = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.csno_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.csno_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.csno_insert.setObjectName("csno_insert")
        self.formLayout_52.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.csno_insert)
        self.horizontalLayout_17.addLayout(self.formLayout_52)
        self.formLayout_65 = QtWidgets.QFormLayout()
        self.formLayout_65.setObjectName("formLayout_65")
        self.label_65 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_65.setObjectName("label_65")
        self.formLayout_65.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_65)
        self.cmno_to_insert = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.cmno_to_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.cmno_to_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmno_to_insert.setObjectName("cmno_to_insert")
        self.formLayout_65.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cmno_to_insert)
        self.horizontalLayout_17.addLayout(self.formLayout_65)
        self.formLayout_66 = QtWidgets.QFormLayout()
        self.formLayout_66.setObjectName("formLayout_66")
        self.label_66 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_66.setObjectName("label_66")
        self.formLayout_66.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_66)
        self.cyear_insert = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.cyear_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.cyear_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cyear_insert.setObjectName("cyear_insert")
        self.formLayout_66.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cyear_insert)
        self.horizontalLayout_17.addLayout(self.formLayout_66)
        self.btn_major_change_insert = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_major_change_insert.setObjectName("btn_major_change_insert")
        self.horizontalLayout_17.addWidget(self.btn_major_change_insert)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.verticalLayout_10.addLayout(self.verticalLayout_14)
        self.table_management.addWidget(self.major_change_page)
        self.grade_page = QtWidgets.QWidget()
        self.grade_page.setObjectName("grade_page")
        self.layoutWidget_6 = QtWidgets.QWidget(self.grade_page)
        self.layoutWidget_6.setGeometry(QtCore.QRect(210, 20, 691, 444))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.grade_table = QtWidgets.QTableWidget(self.layoutWidget_6)
        self.grade_table.setMinimumSize(QtCore.QSize(0, 250))
        self.grade_table.setObjectName("grade_table")
        self.grade_table.setColumnCount(0)
        self.grade_table.setRowCount(0)
        self.verticalLayout_12.addWidget(self.grade_table)
        spacerItem4 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.formLayout_53 = QtWidgets.QFormLayout()
        self.formLayout_53.setObjectName("formLayout_53")
        self.label_53 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_53.setObjectName("label_53")
        self.formLayout_53.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.gsno_search = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.gsno_search.setMinimumSize(QtCore.QSize(50, 0))
        self.gsno_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gsno_search.setObjectName("gsno_search")
        self.formLayout_53.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gsno_search)
        self.horizontalLayout_16.addLayout(self.formLayout_53)
        self.formLayout_59 = QtWidgets.QFormLayout()
        self.formLayout_59.setObjectName("formLayout_59")
        self.label_59 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_59.setObjectName("label_59")
        self.formLayout_59.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_59)
        self.gcno_search = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.gcno_search.setMinimumSize(QtCore.QSize(50, 0))
        self.gcno_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gcno_search.setObjectName("gcno_search")
        self.formLayout_59.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gcno_search)
        self.horizontalLayout_16.addLayout(self.formLayout_59)
        self.btn_grade_search = QtWidgets.QPushButton(self.layoutWidget_6)
        self.btn_grade_search.setObjectName("btn_grade_search")
        self.horizontalLayout_16.addWidget(self.btn_grade_search)
        self.verticalLayout_11.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.formLayout_62 = QtWidgets.QFormLayout()
        self.formLayout_62.setObjectName("formLayout_62")
        self.label_62 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_62.setObjectName("label_62")
        self.formLayout_62.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.gsno_insert = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.gsno_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.gsno_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gsno_insert.setObjectName("gsno_insert")
        self.formLayout_62.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gsno_insert)
        self.horizontalLayout_18.addLayout(self.formLayout_62)
        self.formLayout_64 = QtWidgets.QFormLayout()
        self.formLayout_64.setObjectName("formLayout_64")
        self.label_64 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_64.setObjectName("label_64")
        self.formLayout_64.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.gcno_insert = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.gcno_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.gcno_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gcno_insert.setObjectName("gcno_insert")
        self.formLayout_64.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gcno_insert)
        self.horizontalLayout_18.addLayout(self.formLayout_64)
        self.formLayout_67 = QtWidgets.QFormLayout()
        self.formLayout_67.setObjectName("formLayout_67")
        self.label_67 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_67.setObjectName("label_67")
        self.formLayout_67.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_67)
        self.score_insert = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.score_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.score_insert.setMaximumSize(QtCore.QSize(60, 16777215))
        self.score_insert.setObjectName("score_insert")
        self.formLayout_67.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.score_insert)
        self.horizontalLayout_18.addLayout(self.formLayout_67)
        self.btn_grade_insert = QtWidgets.QPushButton(self.layoutWidget_6)
        self.btn_grade_insert.setObjectName("btn_grade_insert")
        self.horizontalLayout_18.addWidget(self.btn_grade_insert)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.formLayout_71 = QtWidgets.QFormLayout()
        self.formLayout_71.setObjectName("formLayout_71")
        self.label_71 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_71.setObjectName("label_71")
        self.formLayout_71.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_71)
        self.gsno_update = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.gsno_update.setMinimumSize(QtCore.QSize(50, 0))
        self.gsno_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gsno_update.setObjectName("gsno_update")
        self.formLayout_71.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gsno_update)
        self.horizontalLayout_19.addLayout(self.formLayout_71)
        self.formLayout_72 = QtWidgets.QFormLayout()
        self.formLayout_72.setObjectName("formLayout_72")
        self.label_72 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_72.setObjectName("label_72")
        self.formLayout_72.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_72)
        self.gcno_update = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.gcno_update.setMinimumSize(QtCore.QSize(50, 0))
        self.gcno_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gcno_update.setObjectName("gcno_update")
        self.formLayout_72.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gcno_update)
        self.horizontalLayout_19.addLayout(self.formLayout_72)
        self.formLayout_73 = QtWidgets.QFormLayout()
        self.formLayout_73.setObjectName("formLayout_73")
        self.label_73 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_73.setObjectName("label_73")
        self.formLayout_73.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_73)
        self.score_update = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.score_update.setMinimumSize(QtCore.QSize(50, 0))
        self.score_update.setMaximumSize(QtCore.QSize(60, 16777215))
        self.score_update.setObjectName("score_update")
        self.formLayout_73.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.score_update)
        self.horizontalLayout_19.addLayout(self.formLayout_73)
        self.btn_update_update = QtWidgets.QPushButton(self.layoutWidget_6)
        self.btn_update_update.setObjectName("btn_update_update")
        self.horizontalLayout_19.addWidget(self.btn_update_update)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.formLayout_57 = QtWidgets.QFormLayout()
        self.formLayout_57.setObjectName("formLayout_57")
        self.label_57 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_57.setObjectName("label_57")
        self.formLayout_57.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_57)
        self.gsno_delete = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.gsno_delete.setMinimumSize(QtCore.QSize(50, 0))
        self.gsno_delete.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gsno_delete.setObjectName("gsno_delete")
        self.formLayout_57.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gsno_delete)
        self.horizontalLayout_20.addLayout(self.formLayout_57)
        self.formLayout_60 = QtWidgets.QFormLayout()
        self.formLayout_60.setObjectName("formLayout_60")
        self.label_60 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_60.setObjectName("label_60")
        self.formLayout_60.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_60)
        self.gcno_delete = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.gcno_delete.setMinimumSize(QtCore.QSize(50, 0))
        self.gcno_delete.setMaximumSize(QtCore.QSize(80, 16777215))
        self.gcno_delete.setObjectName("gcno_delete")
        self.formLayout_60.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gcno_delete)
        self.horizontalLayout_20.addLayout(self.formLayout_60)
        self.btn_grade_delete = QtWidgets.QPushButton(self.layoutWidget_6)
        self.btn_grade_delete.setObjectName("btn_grade_delete")
        self.horizontalLayout_20.addWidget(self.btn_grade_delete)
        self.verticalLayout_11.addLayout(self.horizontalLayout_20)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.table_management.addWidget(self.grade_page)
        self.award_punishment_page = QtWidgets.QWidget()
        self.award_punishment_page.setObjectName("award_punishment_page")
        self.layoutWidget_14 = QtWidgets.QWidget(self.award_punishment_page)
        self.layoutWidget_14.setGeometry(QtCore.QRect(190, 20, 751, 444))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget_14)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.award_punishment_table = QtWidgets.QTableWidget(self.layoutWidget_14)
        self.award_punishment_table.setMinimumSize(QtCore.QSize(0, 250))
        self.award_punishment_table.setObjectName("award_punishment_table")
        self.award_punishment_table.setColumnCount(0)
        self.award_punishment_table.setRowCount(0)
        self.verticalLayout_13.addWidget(self.award_punishment_table)
        spacerItem5 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem5)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.formLayout_84 = QtWidgets.QFormLayout()
        self.formLayout_84.setObjectName("formLayout_84")
        self.label_84 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_84.setObjectName("label_84")
        self.formLayout_84.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_84)
        self.aid_search = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.aid_search.setMinimumSize(QtCore.QSize(50, 0))
        self.aid_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.aid_search.setObjectName("aid_search")
        self.formLayout_84.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aid_search)
        self.horizontalLayout_21.addLayout(self.formLayout_84)
        self.formLayout_58 = QtWidgets.QFormLayout()
        self.formLayout_58.setObjectName("formLayout_58")
        self.label_58 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_58.setObjectName("label_58")
        self.formLayout_58.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_58)
        self.asno_search = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.asno_search.setMinimumSize(QtCore.QSize(50, 0))
        self.asno_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.asno_search.setObjectName("asno_search")
        self.formLayout_58.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.asno_search)
        self.horizontalLayout_21.addLayout(self.formLayout_58)
        self.formLayout_74 = QtWidgets.QFormLayout()
        self.formLayout_74.setObjectName("formLayout_74")
        self.label_74 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_74.setObjectName("label_74")
        self.formLayout_74.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_74)
        self.atime_search = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.atime_search.setMinimumSize(QtCore.QSize(50, 0))
        self.atime_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.atime_search.setObjectName("atime_search")
        self.formLayout_74.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.atime_search)
        self.horizontalLayout_21.addLayout(self.formLayout_74)
        self.formLayout_83 = QtWidgets.QFormLayout()
        self.formLayout_83.setObjectName("formLayout_83")
        self.label_83 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_83.setObjectName("label_83")
        self.formLayout_83.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_83)
        self.acontent_search = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.acontent_search.setMinimumSize(QtCore.QSize(50, 0))
        self.acontent_search.setMaximumSize(QtCore.QSize(80, 16777215))
        self.acontent_search.setObjectName("acontent_search")
        self.formLayout_83.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.acontent_search)
        self.horizontalLayout_21.addLayout(self.formLayout_83)
        self.btn_award_punishment_search = QtWidgets.QPushButton(self.layoutWidget_14)
        self.btn_award_punishment_search.setObjectName("btn_award_punishment_search")
        self.horizontalLayout_21.addWidget(self.btn_award_punishment_search)
        self.verticalLayout_15.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.formLayout_75 = QtWidgets.QFormLayout()
        self.formLayout_75.setObjectName("formLayout_75")
        self.label_75 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_75.setObjectName("label_75")
        self.formLayout_75.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_75)
        self.asno_insert = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.asno_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.asno_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.asno_insert.setObjectName("asno_insert")
        self.formLayout_75.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.asno_insert)
        self.horizontalLayout_22.addLayout(self.formLayout_75)
        self.formLayout_85 = QtWidgets.QFormLayout()
        self.formLayout_85.setObjectName("formLayout_85")
        self.label_85 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_85.setObjectName("label_85")
        self.formLayout_85.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_85)
        self.acontent_insert = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.acontent_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.acontent_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.acontent_insert.setObjectName("acontent_insert")
        self.formLayout_85.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.acontent_insert)
        self.horizontalLayout_22.addLayout(self.formLayout_85)
        self.formLayout_77 = QtWidgets.QFormLayout()
        self.formLayout_77.setObjectName("formLayout_77")
        self.label_77 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_77.setObjectName("label_77")
        self.formLayout_77.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_77)
        self.atime_insert = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.atime_insert.setMinimumSize(QtCore.QSize(50, 0))
        self.atime_insert.setMaximumSize(QtCore.QSize(80, 16777215))
        self.atime_insert.setObjectName("atime_insert")
        self.formLayout_77.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.atime_insert)
        self.horizontalLayout_22.addLayout(self.formLayout_77)
        self.btn_award_punishment_insert = QtWidgets.QPushButton(self.layoutWidget_14)
        self.btn_award_punishment_insert.setObjectName("btn_award_punishment_insert")
        self.horizontalLayout_22.addWidget(self.btn_award_punishment_insert)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.formLayout_76 = QtWidgets.QFormLayout()
        self.formLayout_76.setObjectName("formLayout_76")
        self.label_76 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_76.setObjectName("label_76")
        self.formLayout_76.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_76)
        self.aid_update = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.aid_update.setMinimumSize(QtCore.QSize(50, 0))
        self.aid_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.aid_update.setObjectName("aid_update")
        self.formLayout_76.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aid_update)
        self.horizontalLayout_23.addLayout(self.formLayout_76)
        self.formLayout_86 = QtWidgets.QFormLayout()
        self.formLayout_86.setObjectName("formLayout_86")
        self.label_86 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_86.setObjectName("label_86")
        self.formLayout_86.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_86)
        self.acontent_update = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.acontent_update.setMinimumSize(QtCore.QSize(50, 0))
        self.acontent_update.setMaximumSize(QtCore.QSize(80, 16777215))
        self.acontent_update.setObjectName("acontent_update")
        self.formLayout_86.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.acontent_update)
        self.horizontalLayout_23.addLayout(self.formLayout_86)
        self.btn_award_punishment_update = QtWidgets.QPushButton(self.layoutWidget_14)
        self.btn_award_punishment_update.setObjectName("btn_award_punishment_update")
        self.horizontalLayout_23.addWidget(self.btn_award_punishment_update)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.formLayout_87 = QtWidgets.QFormLayout()
        self.formLayout_87.setObjectName("formLayout_87")
        self.label_87 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_87.setObjectName("label_87")
        self.formLayout_87.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_87)
        self.aid_delete = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.aid_delete.setMinimumSize(QtCore.QSize(50, 0))
        self.aid_delete.setMaximumSize(QtCore.QSize(80, 16777215))
        self.aid_delete.setObjectName("aid_delete")
        self.formLayout_87.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.aid_delete)
        self.horizontalLayout_24.addLayout(self.formLayout_87)
        self.btn_award_punishment_delete = QtWidgets.QPushButton(self.layoutWidget_14)
        self.btn_award_punishment_delete.setObjectName("btn_award_punishment_delete")
        self.horizontalLayout_24.addWidget(self.btn_award_punishment_delete)
        self.verticalLayout_15.addLayout(self.horizontalLayout_24)
        self.verticalLayout_13.addLayout(self.verticalLayout_15)
        self.table_management.addWidget(self.award_punishment_page)
        self.horizontalLayout_25.addWidget(self.table_management)

        self.retranslateUi(Form)
        self.table_management.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_student.setText(_translate("Form", "student management"))
        self.btn_course.setText(_translate("Form", "course management"))
        self.btn_major.setText(_translate("Form", "major management"))
        self.btn_major_change.setText(_translate("Form", "major change"))
        self.btn_grade.setText(_translate("Form", "grade management"))
        self.btn_award_punishment.setText(_translate("Form", "award/punishment"))
        self.label.setText(_translate("Form", "student ID:"))
        self.label_2.setText(_translate("Form", "name:"))
        self.label_3.setText(_translate("Form", "sex:"))
        self.sex_search.setItemText(1, _translate("Form", "walmart bag"))
        self.sex_search.setItemText(2, _translate("Form", "male"))
        self.sex_search.setItemText(3, _translate("Form", "female"))
        self.label_4.setText(_translate("Form", "major ID:"))
        self.label_14.setText(_translate("Form", "grades:"))
        self.label_5.setText(_translate("Form", "year:"))
        self.btn_student_search.setText(_translate("Form", "search"))
        self.label_6.setText(_translate("Form", "*student ID:"))
        self.label_7.setText(_translate("Form", "*name:"))
        self.label_8.setText(_translate("Form", "*sex:"))
        self.sex_insert.setItemText(0, _translate("Form", "walmart bag"))
        self.sex_insert.setItemText(1, _translate("Form", "male"))
        self.sex_insert.setItemText(2, _translate("Form", "female"))
        self.label_9.setText(_translate("Form", "*major ID:"))
        self.label_10.setText(_translate("Form", "*year:"))
        self.label_11.setText(_translate("Form", "phone:"))
        self.label_12.setText(_translate("Form", "photo:"))
        self.btn_student_insert.setText(_translate("Form", "insert"))
        self.label_15.setText(_translate("Form", "*student ID:"))
        self.label_16.setText(_translate("Form", "name:"))
        self.label_17.setText(_translate("Form", "sex:"))
        self.sex_update.setItemText(1, _translate("Form", "walmart bag"))
        self.sex_update.setItemText(2, _translate("Form", "male"))
        self.sex_update.setItemText(3, _translate("Form", "female"))
        self.label_20.setText(_translate("Form", "phone:"))
        self.label_21.setText(_translate("Form", "photo:"))
        self.btn_student_update.setText(_translate("Form", "update"))
        self.label_18.setText(_translate("Form", "*student ID:"))
        self.btn_student_delete.setText(_translate("Form", "delete"))
        self.label_19.setText(_translate("Form", "course ID:"))
        self.label_22.setText(_translate("Form", "name:"))
        self.btn_course_search.setText(_translate("Form", "search"))
        self.label_27.setText(_translate("Form", "*course ID:"))
        self.label_28.setText(_translate("Form", "*name:"))
        self.btn_course_insert.setText(_translate("Form", "insert"))
        self.label_34.setText(_translate("Form", "*course ID:"))
        self.label_35.setText(_translate("Form", "*name:"))
        self.btn_course_update.setText(_translate("Form", "update"))
        self.label_23.setText(_translate("Form", "major ID:"))
        self.label_24.setText(_translate("Form", "name:"))
        self.btn_major_search.setText(_translate("Form", "search"))
        self.label_29.setText(_translate("Form", "*major ID:"))
        self.label_30.setText(_translate("Form", "*name:"))
        self.btn_major_insert.setText(_translate("Form", "insert"))
        self.label_36.setText(_translate("Form", "*major ID:"))
        self.label_37.setText(_translate("Form", "*name:"))
        self.btn_major_update.setText(_translate("Form", "update"))
        self.label_51.setText(_translate("Form", "student ID:"))
        self.label_54.setText(_translate("Form", "old major ID:"))
        self.label_55.setText(_translate("Form", "new major ID:"))
        self.label_56.setText(_translate("Form", "change year:"))
        self.btn_major_change_search.setText(_translate("Form", "search"))
        self.label_52.setText(_translate("Form", "*student ID:"))
        self.label_65.setText(_translate("Form", "*new major ID:"))
        self.label_66.setText(_translate("Form", "*change year:"))
        self.btn_major_change_insert.setText(_translate("Form", "insert"))
        self.label_53.setText(_translate("Form", "student ID:"))
        self.label_59.setText(_translate("Form", "course ID:"))
        self.btn_grade_search.setText(_translate("Form", "search"))
        self.label_62.setText(_translate("Form", "*student ID:"))
        self.label_64.setText(_translate("Form", "*course ID:"))
        self.label_67.setText(_translate("Form", "*grade:"))
        self.btn_grade_insert.setText(_translate("Form", "insert"))
        self.label_71.setText(_translate("Form", "*student ID:"))
        self.label_72.setText(_translate("Form", "*course ID:"))
        self.label_73.setText(_translate("Form", "*grade:"))
        self.btn_update_update.setText(_translate("Form", "update"))
        self.label_57.setText(_translate("Form", "*student ID:"))
        self.label_60.setText(_translate("Form", "*course ID:"))
        self.btn_grade_delete.setText(_translate("Form", "delete"))
        self.label_84.setText(_translate("Form", "index:"))
        self.label_58.setText(_translate("Form", "student ID:"))
        self.label_74.setText(_translate("Form", "time:"))
        self.label_83.setText(_translate("Form", "content:"))
        self.btn_award_punishment_search.setText(_translate("Form", "search"))
        self.label_75.setText(_translate("Form", "*student ID:"))
        self.label_85.setText(_translate("Form", "*content:"))
        self.label_77.setText(_translate("Form", "time:"))
        self.btn_award_punishment_insert.setText(_translate("Form", "insert"))
        self.label_76.setText(_translate("Form", "*index:"))
        self.label_86.setText(_translate("Form", "*content:"))
        self.btn_award_punishment_update.setText(_translate("Form", "update"))
        self.label_87.setText(_translate("Form", "*index:"))
        self.btn_award_punishment_delete.setText(_translate("Form", "delete"))

import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox, QTableWidgetItem, QWidget, QLabel
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPixmap
import pymysql
import base64
from datetime import datetime

class MyMainForm(QMainWindow, Ui_Form):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.connect_btn()
        
        self.db = pymysql.connect(
            host='localhost',
            user='root',
            password='123456',
            port=3306,
            database='lab2',
            charset='utf8'
        )
    
    def connect_btn(self):
        self.btn_student.clicked.connect(self.show_student_page)
        self.btn_course.clicked.connect(self.show_course_page)
        self.btn_major.clicked.connect(self.show_major_page)
        self.btn_major_change.clicked.connect(self.show_major_change_page)
        self.btn_grade.clicked.connect(self.show_grade_page)
        self.btn_award_punishment.clicked.connect(self.show_award_punishment_page)
        
        self.btn_student_search.clicked.connect(self.student_search)
        self.btn_student_insert.clicked.connect(self.student_insert)
        self.btn_student_update.clicked.connect(self.student_update)
        self.btn_student_delete.clicked.connect(self.student_delete)
        
        self.btn_course_search.clicked.connect(self.course_search)
        self.btn_course_insert.clicked.connect(self.course_insert)
        self.btn_course_update.clicked.connect(self.course_update)

        self.btn_major_search.clicked.connect(self.major_search)
        self.btn_major_insert.clicked.connect(self.major_insert)
        self.btn_major_update.clicked.connect(self.major_update)
        
        self.btn_major_change_search.clicked.connect(self.major_change_search)
        self.btn_major_change_insert.clicked.connect(self.major_change_insert)

        self.btn_grade_search.clicked.connect(self.grade_search)
        self.btn_grade_insert.clicked.connect(self.grade_insert)
        self.btn_update_update.clicked.connect(self.grade_update)
        self.btn_grade_delete.clicked.connect(self.grade_delete)
        
        self.btn_award_punishment_search.clicked.connect(self.award_punishment_search)
        self.btn_award_punishment_insert.clicked.connect(self.award_punishment_insert)
        self.btn_award_punishment_update.clicked.connect(self.award_punishment_update)
        self.btn_award_punishment_delete.clicked.connect(self.award_punishment_delete)
    
    def exec_sql(self, sql, values=None):
        with self.db.cursor() as cursor:
            if values:
                cursor.execute(sql, values)
            else:
                cursor.execute(sql)
                return cursor.fetchall()

    def show_table(self, table, results, header):
        table.setRowCount(len(results))
        table.setColumnCount(len(header))
        for i, result in enumerate(results):
            for j, value in enumerate(result):
                if value is not None:
                    table.setItem(i, j, QTableWidgetItem(str(value)))
        table.setHorizontalHeaderLabels(header)

    def show_student_page(self):
        self.table_management.setCurrentWidget(self.student_page)
        self.show_student_table()
    
    def show_course_page(self):
        self.table_management.setCurrentWidget(self.course_page)
        self.show_course_table()
        
    def show_major_page(self):
        self.table_management.setCurrentWidget(self.major_page)
        self.show_major_table()
        
    def show_major_change_page(self):
        self.table_management.setCurrentWidget(self.major_change_page)
        self.show_major_change_table()
        
    def show_grade_page(self):
        self.table_management.setCurrentWidget(self.grade_page)
        self.show_grade_table()
        
    def show_award_punishment_page(self):
        self.table_management.setCurrentWidget(self.award_punishment_page)
        self.show_award_punishment_table()

    def show_student_table(self):
        sql = 'select * from student'
        try:
            results = self.exec_sql(sql)
            self.student_table.setRowCount(len(results))
            self.student_table.setColumnCount(8)
            for i, result in enumerate(results):
                for j, value in enumerate(result):
                    if value is not None:
                        if j != 7:
                            self.student_table.setItem(i, j, QTableWidgetItem(str(value)))
                        else:
                            blob = base64.b64decode(value)
                            pixmap = QPixmap()
                            pixmap.loadFromData(blob)
                            # item = QTableWidgetItem()
                            # item.setData(Qt.DecorationRole, pixmap.scaled(self.student_table.columnWidth(j), self.student_table.rowHeight(i), Qt.KeepAspectRatio, Qt.SmoothTransformation))
                            # self.student_table.setItem(i, j, item)
                            label = QLabel()
                            label.setPixmap(pixmap.scaled(self.student_table.columnWidth(j), self.student_table.rowHeight(i), Qt.KeepAspectRatio, Qt.SmoothTransformation))
                            self.student_table.setCellWidget(i, j, label)
            header = ['student ID', 'name', 'sex', 'major ID', 'year', 'grade', 'phone', 'photo']
            self.student_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', 'Error when selecting student table')
            print(e)         
            
    def student_search(self):
        sno = self.sno_search.text()
        sname = self.sname_search.text()
        sex = self.sex_search.currentText()
        smno = self.smno_search.text()
        sgrade = self.sgrade_search.text()
        syear = self.syear_search.text()
    
        name_dict = {0: 'sno', 1: 'sname', 2: 'sex', 3: 'smno', 4: 'sgrade', 5: 'syear'}
        conditions = [sno, sname, sex, smno, sgrade, syear]
        exist_len = len([_ for _ in conditions if _])
        sql = 'select * from student'
        if exist_len > 0:
            first = True
            for i, condition in enumerate(conditions):
                if condition:
                    if first == True:
                        sql += f' where {name_dict[i]} = \'{condition}\''
                        first = False
                    else:
                        sql += f' and {name_dict[i]} = \'{condition}\''
        try:
            results = self.exec_sql(sql)
            if not results:
                QMessageBox.information(self, 'tips', 'No record meets the conditions')
            else:
                self.student_table.setRowCount(len(results))
                self.student_table.setColumnCount(8)
                for i, result in enumerate(results):
                    for j, value in enumerate(result):
                        if value is not None:
                            if j != 7:
                                self.student_table.setItem(i, j, QTableWidgetItem(str(value)))
                            else:
                                blob = base64.b64decode(value)
                                pixmap = QPixmap()
                                pixmap.loadFromData(blob)
                                # item = QTableWidgetItem()
                                # item.setData(Qt.DecorationRole, pixmap.scaled(self.student_table.columnWidth(j), self.student_table.rowHeight(i), Qt.KeepAspectRatio, Qt.SmoothTransformation))
                                # self.student_table.setItem(i, j, item)
                                label = QLabel()
                                label.setPixmap(pixmap.scaled(self.student_table.columnWidth(j), self.student_table.rowHeight(i), Qt.KeepAspectRatio, Qt.SmoothTransformation))
                                self.student_table.setCellWidget(i, j, label)
                header = ['student ID', 'name', 'sex', 'major ID', 'year', 'grade', 'phone', 'photo']
                self.student_table.setHorizontalHeaderLabels(header)
        
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when searching student:\n{e}')
    
    def student_insert(self):
        sno = self.sno_insert.text()
        sname = self.sname_insert.text()
        sex = self.sex_insert.currentText()
        smno = self.smno_insert.text()
        syear = self.syear_insert.text()
        sphone = self.sphone_insert.text()
        sphoto = self.sphoto_insert.text()
        
        try:
            syear = int(syear)
        except:
            QMessageBox.information(self, 'tips', 'year must be an integer')
            return
            
        if sno and sname and sex and smno and syear:
            insert_label = '(sno, sname, sex, smno, syear, sgrade'
            insert_value = list((sno, sname, sex, smno, syear, 0))
            if sphone:
                insert_label += ', sphone'
                insert_value.append(sphone)
            if sphoto:
                with open(sphoto, 'rb') as f:
                    blob = base64.b64encode(f.read())
                insert_label += ', sphoto'
                insert_value.append(blob)
            insert_label += ')'
            sql = f'insert into student {insert_label} values ({", ".join(["%s"]*len(insert_value))})'
            try:
                self.exec_sql(sql, insert_value)
                self.db.commit()
                self.show_student_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when inserting student:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'Information marked with an asterisk(*) is required')
            
    def student_update(self):
        sno = self.sno_update.text()
        sname = self.sname_update.text()
        sex = self.sex_update.currentText()
        sphone = self.sphone_update.text()
        sphoto = self.sphoto_update.text()
    
        if sno:
            update_label = []
            update_value = []
            if sname:
                update_label.append('sname = %s')
                update_value.append(sname)
            if sex:
                update_label.append('sex = %s')
                update_value.append(sex)
            if sphone:
                update_label.append('sphone = %s')
                update_value.append(sphone)
            if sphoto:
                with open(sphoto, 'rb') as f:
                    blob = base64.b64encode(f.read())
                update_label.append('sphoto = %s')
                update_value.append(blob)
                
            if not update_label:
                return
            
            sql = f'update student set {", ".join(update_label)} where sno = %s'
            update_value.append(sno)
            try:
                self.exec_sql(sql, update_value)
                self.db.commit()
                self.show_student_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when updating student:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'student ID is required')
    
    def student_delete(self):
        # delete_student(sno) procedure
        sno = self.sno_delete.text()
        if sno:
            sql = 'call delete_student(%s)'
            try:
                self.exec_sql(sql, sno)
                self.db.commit()
                self.show_student_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when deleting student:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'student ID is required')
            
    def show_course_table(self):
        sql = 'select * from course'
        try:
            results = self.exec_sql(sql)
            header = ['course ID', 'name']
            self.show_table(self.course_table, results, header)
            self.course_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when selecting course table:\n{e}')
    
    def course_search(self):
        cno = self.cno_search.text()
        cname = self.cname_search.text()
        
        name_dict = {0: 'cno', 1: 'cname'}
        conditions = [cno, cname]
        exist_len = len([_ for _ in conditions if _])
        sql = 'select * from course'
        if exist_len > 0:
            first = True
            for i, condition in enumerate(conditions):
                if condition:
                    if first == True:
                        sql += f' where {name_dict[i]} = \'{condition}\''
                        first = False
                    else:
                        sql += f' and {name_dict[i]} = \'{condition}\''
        try:
            results = self.exec_sql(sql)
            if not results:
                QMessageBox.information(self, 'tips', 'No record meets the conditions')
            else:
                header = ['course ID', 'name']
                self.show_table(self.course_table, results, header)
                self.course_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when searching course:\n{e}')
    
    def course_insert(self):
        cno = self.cno_insert.text()
        cname = self.cname_insert.text()
        
        if cno and cname:
            sql = 'insert into course (cno, cname) values (%s, %s)'
            try:
                self.exec_sql(sql, (cno, cname))
                self.db.commit()
                self.show_course_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when inserting course:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'Information marked with an asterisk(*) is required')
    
    def course_update(self):
        cno = self.cno_update.text()
        cname = self.cname_update.text()
        
        if cno:
            if not cname:
                return
            
            sql = f'update course set cname = %s where cno = %s'
            try:
                self.exec_sql(sql, (cname, cno))
                self.db.commit()
                self.show_course_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when updating course:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'course ID is required')
    
    def show_major_table(self):
        sql = 'select * from major'
        try:
            results = self.exec_sql(sql)
            header = ['major ID', 'name']
            self.show_table(self.major_table, results, header)
            self.major_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when selecting major table:\n{e}')
    
    def major_search(self):
        mno = self.mno_search.text()
        mname = self.mname_search.text()
        
        name_dict = {0: 'mno', 1: 'mname'}
        conditions = [mno, mname]
        exist_len = len([_ for _ in conditions if _])
        sql = 'select * from major'
        if exist_len > 0:
            first = True
            for i, condition in enumerate(conditions):
                if condition:
                    if first == True:
                        sql += f' where {name_dict[i]} = \'{condition}\''
                        first = False
                    else:
                        sql += f' and {name_dict[i]} = \'{condition}\''
        try:
            results = self.exec_sql(sql)
            if not results:
                QMessageBox.information(self, 'tips', 'No record meets the conditions')
            else:
                header = ['major ID', 'name']
                self.show_table(self.major_table, results, header)
                self.major_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when searching major:\n{e}')
    
    def major_insert(self):
        mno = self.mno_insert.text()
        mname = self.mname_insert.text()
        
        if mno and mname:
            sql = 'insert into major (mno, mname) values (%s, %s)'
            try:
                self.exec_sql(sql, (mno, mname))
                self.db.commit()
                self.show_major_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when inserting major:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'Information marked with an asterisk(*) is required')
    
    def major_update(self):
        mno = self.mno_update.text()
        mname = self.mname_update.text()
        
        if mno:
            if not mname:
                return
            
            sql = f'update major set mname = %s where mno = %s'
            try:
                self.exec_sql(sql, (mname, mno))
                self.db.commit()
                self.show_major_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when updating major:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'major ID is required')
    
    def show_major_change_table(self):
        sql = 'select * from major_change'
        try:
            results = self.exec_sql(sql)
            header = ['student ID', 'old major ID', 'new major ID', 'change year']
            self.show_table(self.major_change_table, results, header)
            self.major_change_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when selecting major change table:\n{e}')
    
    def major_change_search(self):
        csno = self.csno_search.text()
        cmno_from = self.cmno_from_search.text()
        cmno_to = self.cmno_to_search.text()
        cyear = self.cyear_search.text()
        
        name_dict = {0: 'csno', 1: 'cmno_from', 2: 'cmno_to', 3: 'cyear'}
        conditions = [csno, cmno_from, cmno_to, cyear]
        exist_len = len([_ for _ in conditions if _])
        sql = 'select * from major_change'
        if exist_len > 0:
            first = True
            for i, condition in enumerate(conditions):
                if condition:
                    if first == True:
                        sql += f' where {name_dict[i]} = \'{condition}\''
                        first = False
                    else:
                        sql += f' and {name_dict[i]} = \'{condition}\''
        try:
            results = self.exec_sql(sql)
            if not results:
                QMessageBox.information(self, 'tips', 'No record meets the conditions')
            else:
                header = ['student ID', 'old major ID', 'new major ID', 'change year']
                self.show_table(self.major_change_table, results, header)
                self.major_change_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when searching major change:\n{e}')
    
    def major_change_insert(self):
        # change_major(sno, new major id, year) procedure 
        csno = self.csno_insert.text()
        cmno_to = self.cmno_to_insert.text()
        cyear = self.cyear_insert.text()

        try:
            cyear = int(cyear)
        except:
            QMessageBox.information(self, 'tips', 'year must be an integer')
            return
        
        if csno and cmno_to and cyear:
            sql = 'call change_major(%s, %s, %s)'
            try:
                self.exec_sql(sql, (csno, cmno_to, cyear))
                self.db.commit()
                self.show_major_change_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when inserting major change:\n{e}')
    
    def show_grade_table(self):
        sql = 'select * from grade'
        try:
            results = self.exec_sql(sql)
            header = ['student ID', 'course ID', 'grade']
            self.show_table(self.grade_table, results, header)
            self.grade_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when selecting grade table:\n{e}')
    
    def grade_search(self):
        gsno = self.gsno_search.text()
        gcno = self.gcno_search.text()
        
        name_dict = {0: 'gsno', 1: 'gcno'}
        conditions = [gsno, gcno]
        exist_len = len([_ for _ in conditions if _])
        sql = 'select * from grade'
        if exist_len > 0:
            first = True
            for i, condition in enumerate(conditions):
                if condition:
                    if first == True:
                        sql += f' where {name_dict[i]} = \'{condition}\''
                        first = False
                    else:
                        sql += f' and {name_dict[i]} = \'{condition}\''
        try:
            results = self.exec_sql(sql)
            if not results:
                QMessageBox.information(self, 'tips', 'No record meets the conditions')
            else:
                header = ['student ID', 'course ID', 'grade']
                self.show_table(self.grade_table, results, header)
                self.grade_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when searching grade:\n{e}')
    
    def grade_insert(self):
        gsno = self.gsno_insert.text()
        gcno = self.gcno_insert.text()
        score = self.score_insert.text()
        
        try:
            score = int(score)
        except:
            QMessageBox.information(self, 'tips', 'grade must be an integer')
            return
        
        if gsno and gcno and score:
            sql = 'insert into grade (gsno, gcno, score) values (%s, %s, %s)'
            try:
                self.exec_sql(sql, (gsno, gcno, score))
                self.db.commit()
                self.show_grade_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when inserting grade:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'Information marked with an asterisk(*) is required')
    
    def grade_update(self):
        gsno = self.gsno_update.text()
        gcno = self.gcno_update.text()
        score = self.score_update.text()
        
        try:
            score = int(score)
        except:
            QMessageBox.information(self, 'tips', 'grade must be an integer')
            return
        
        if gsno and gcno:
            sql = 'update grade set score = %s where gsno = %s and gcno = %s'
            try:
                self.exec_sql(sql, (score, gsno, gcno))
                self.db.commit()
                self.show_grade_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when updating grade:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'student ID and course ID are required')
    
    def grade_delete(self):
        gsno = self.gsno_delete.text()
        gcno = self.gcno_delete.text()
        
        if gsno and gcno:
            sql = 'delete from grade where gsno = %s and gcno = %s'
            try:
                self.exec_sql(sql, (gsno, gcno))
                self.db.commit()
                self.show_grade_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when deleting grade:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'student ID and course ID are required')
    
    def show_award_punishment_table(self):
        sql = 'select * from award_punish'
        try:
            results = self.exec_sql(sql)
            header = ['index', 'student ID', 'time', 'content']
            self.show_table(self.award_punishment_table, results, header)
            self.award_punishment_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when selecting award punishment table:\n{e}')
    
    def award_punishment_search(self):
        aid = self.aid_search.text()
        asno = self.asno_search.text()
        atime = self.atime_search.text()
        acontent = self.acontent_search.text()
        
        name_dict = {0: 'aid', 1: 'asno', 2: 'atime', 3: 'acontent'}
        conditions = [aid, asno, atime, acontent]
        exist_len = len([_ for _ in conditions if _])
        sql = 'select * from award_punish'
        if exist_len > 0:
            first = True
            for i, condition in enumerate(conditions):
                if condition:
                    if first == True:
                        sql += f' where {name_dict[i]} = \'{condition}\''
                        first = False
                    else:
                        sql += f' and {name_dict[i]} = \'{condition}\''
        try:
            results = self.exec_sql(sql)
            if not results:
                QMessageBox.information(self, 'tips', 'No record meets the conditions')
            else:
                header = ['index', 'student ID', 'time', 'content']
                self.show_table(self.award_punishment_table, results, header)
                self.award_punishment_table.setHorizontalHeaderLabels(header)
        except Exception as e:
            QMessageBox.information(self, 'tips', f'Error when searching award punishment:\n{e}')
    
    def award_punishment_insert(self):
        # insert_award_punish(sno, content, time) procedure
        asno = self.asno_insert.text()
        atime = self.atime_insert.text()
        acontent = self.acontent_insert.text()
        
        if asno and acontent:
            if atime:
                try:
                    atime = str(datetime.strptime(atime, '%Y-%m-%d'))[:10]
                except:
                    QMessageBox.information(self, 'tips', 'time must be in the format of yyyy-mm-dd')
                    return
            
            sql = 'call insert_award_punish(%s, %s, %s)'
            try:
                self.exec_sql(sql, (asno, acontent, atime))
                self.db.commit()
                self.show_award_punishment_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when inserting award punishment:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'Information marked with an asterisk(*) is required')
            
        
    def award_punishment_update(self):
        aid = self.aid_update.text()
        acontent = self.acontent_update.text()
        
        try:
            aid = int(aid)
        except:
            QMessageBox.information(self, 'tips', 'index must be an integer')
            return

        if aid:
            if not acontent:
                return
            
            sql = 'update award_punish set acontent = %s where aid = %s'
            try:
                self.exec_sql(sql, (acontent, aid))
                self.db.commit()
                self.show_award_punishment_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when updating award punishment:\n{e}')
    
    def award_punishment_delete(self):
        aid = self.aid_delete.text()
        
        if aid:
            sql = 'delete from award_punish where aid = %s'
            try:
                self.exec_sql(sql, aid)
                self.db.commit()
                self.show_award_punishment_table()
            except Exception as e:
                QMessageBox.information(self, 'tips', f'Error when deleting award punishment:\n{e}')
        else:
            QMessageBox.information(self, 'tips', 'index is required')
    
if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = MyMainForm()
    mainWindow.show()
    mainWindow.show_student_page()
    sys.exit(app.exec_())